name: Pruebas E2E

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-e2e:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar aplicación
        run: npm run build

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas E2E
        run: npm run test:e2e
        env:
          CI: true
          # Variables de entorno para pruebas
          NODE_ENV: test
          DEBUG_MODE: false

      - name: Subir resultados de pruebas
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.node-version }}
          path: |
            test-results/
            tests/screenshots/
          retention-days: 30

      - name: Subir reporte HTML
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.os }}-${{ matrix.node-version }}
          path: playwright-report/
          retention-days: 30

  test-e2e-headed:
    # Pruebas con interfaz gráfica solo en Ubuntu para debugging
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar aplicación
        run: npm run build

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas E2E con interfaz
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npm run test:e2e:headed
        env:
          CI: true
          NODE_ENV: test
          DEBUG_MODE: false

      - name: Subir capturas de debugging
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-screenshots
          path: tests/screenshots/
          retention-days: 7
